const actionTypes = {

	GET_USER_REQUESTED: 'GET_USER_REQUESTED',
	GET_USER_REJECTED: 'GET_USER_REJECTED',
	GET_USER_FULFILLED: 'GET_USER_FULFILLED',	

	GET_NETWORKS_REQUESTED: 'GET_NETWORKS_REQUESTED',
	GET_NETWORKS_REJECTED: 'GET_NETWORKS_REJECTED',
	GET_NETWORKS_FULFILLED: 'GET_NETWORKS_FULFILLED',
	
	NETWORKS_CHANGED: 'NETWORKS_CHANGED',

	GET_NETWORK_HISTORY_ITEM_REQUESTED: 'GET_NETWORK_HISTORY_ITEM_REQUESTED',
	GET_NETWORK_HISTORY_ITEM_REJECTED: 'GET_NETWORK_HISTORY_ITEM_REJECTED',
	GET_NETWORK_HISTORY_ITEM_FULFILLED: 'GET_NETWORK_HISTORY_ITEM_FULFILLED',

	CREATE_NETWORK_HISTORY_ITEM_REQUESTED: 'CREATE_NETWORK_HISTORY_ITEM_REQUESTED',
	CREATE_NETWORK_HISTORY_ITEM_REJECTED: 'CREATE_NETWORK_HISTORY_ITEM_REJECTED',
	CREATE_NETWORK_HISTORY_ITEM_FULFILLED: 'CREATE_NETWORK_HISTORY_ITEM_FULFILLED',

	// not implemented
	CREATE_NETWORK_REQUESTED: 'CREATE_NETWORK_REQUESTED',
	CREATE_NETWORK_REJECTED: 'CREATE_NETWORK_REJECTED',
	CREATE_NETWORK_FULFILLED: 'CREATE_NETWORK_FULFILLED',
	
	// not implemented
	GET_NETWORK_REQUESTED: 'CREATE_NETWORK_REQUESTED',
	GET_NETWORK_REJECTED: 'CREATE_NETWORK_REJECTED',
	GET_NETWORK_FULFILLED: 'CREATE_NETWORK_FULFILLED',

	UPDATE_NETWORK_REQUESTED: 'UPDATE_NETWORK_REQUESTED',
	UPDATE_NETWORK_REJECTED: 'UPDATE_NETWORK_REJECTED',
	UPDATE_NETWORK_FULFILLED: 'UPDATE_NETWORK_FULFILLED',
	
	// not implemented
	DELETE_NETWORK_REQUESTED: 'DELETE_NETWORK_REQUESTED',
	DELETE_NETWORK_REJECTED: 'DELETE_NETWORK_REJECTED',
	DELETE_NETWORK_FULFILLED: 'DELETE_NETWORK_FULFILLED'

}

export default actionTypes;