export default {

  NETWORK_HISTORIES_CHANGED: 'NETWORK_HISTORIES_CHANGED',
  
  GET_NETWORK_HISTORIES_REQUESTED: 'GET_NETWORK_HISTORIES_REQUESTED',
  GET_NETWORK_HISTORIES_REJECTED: 'GET_NETWORK_HISTORIES_REJECTED',
  GET_NETWORK_HISTORIES_FULFILLED: 'GET_NETWORK_HISTORIES_FULFILLED',

  // ACTIONS
  GET_NETWORK_HISTORY_ITEM_REQUESTED: 'GET_NETWORK_HISTORY_ITEM_REQUESTED',
  GET_NETWORK_HISTORY_ITEM_REJECTED: 'GET_NETWORK_HISTORY_ITEM_REJECTED',
  GET_NETWORK_HISTORY_ITEM_FULFILLED: 'GET_NETWORK_HISTORY_ITEM_FULFILLED',

  CREATE_NETWORK_HISTORY_ITEM_REQUESTED: 'CREATE_NETWORK_HISTORY_ITEM_REQUESTED',
  CREATE_NETWORK_HISTORY_ITEM_REJECTED: 'CREATE_NETWORK_HISTORY_ITEM_REJECTED',
  CREATE_NETWORK_HISTORY_ITEM_FULFILLED: 'CREATE_NETWORK_HISTORY_ITEM_FULFILLED',
  
};
