// export default {
// 	LINES_CHANGED: 'LINES_CHANGED',

// 	CREATE_LINE_REQUESTED: 'CREATE_LINE_REQUESTED',
// 	CREATE_LINE_REJECTED: 'CREATE_LINE_REJECTED',
// 	CREATE_LINE_FULFILLED: 'CREATE_LINE_FULFILLED',
// };