export default {
  // ACTIONS
  GET_NETWORK_HISTORY_ITEM_REQUESTED: 'GET_NETWORK_HISTORY_ITEM_REQUESTED',
  GET_NETWORK_HISTORY_ITEM_REJECTED: 'GET_NETWORK_HISTORY_ITEM_REJECTED',
  GET_NETWORK_HISTORY_ITEM_FULFILLED: 'GET_NETWORK_HISTORY_ITEM_FULFILLED',

  CREATE_NETWORK_HISTORY_ITEM_REQUESTED: 'CREATE_NETWORK_HISTORY_ITEM_REQUESTED',
  CREATE_NETWORK_HISTORY_ITEM_REJECTED: 'CREATE_NETWORK_HISTORY_ITEM_REJECTED',
  CREATE_NETWORK_HISTORY_ITEM_FULFILLED: 'CREATE_NETWORK_HISTORY_ITEM_FULFILLED',
  
};
