export default {

  PENDING_CHANGED: 'PENDING_CHANGED',

  CREATE_PENDING_DELETION_REQUESTED: 'CREATE_PENDING_DELETION_REQUESTED',
  CREATE_PENDING_DELETION_REJECTED: 'CREATE_PENDING_DELETION_REJECTED',
  CREATE_PENDING_DELETION_FULFILLED: 'CREATE_PENDING_DELETION_FULFILLED',

  GET_PENDING_DELETION_REQUESTED: 'GET_PENDING_DELETION_REQUESTED',
  GET_PENDING_DELETION_REJECTED: 'GET_PENDING_DELETION_REJECTED',
  GET_PENDING_DELETION_FULFILLED: 'GET_PENDING_DELETION_FULFILLED',

  UPDATE_PENDING_DELETION_REQUESTED: 'UPDATE_PENDING_DELETION_REQUESTED',
  UPDATE_PENDING_DELETION_REJECTED: 'UPDATE_PENDING_DELETION_REJECTED',
  UPDATE_PENDING_DELETION_FULFILLED: 'UPDATE_PENDING_DELETION_FULFILLED',

  DELETE_PENDING_DELETION_REQUESTED: 'DELETE_PENDING_DELETION_REQUESTED',
  DELETE_PENDING_DELETION_REJECTED: 'DELETE_PENDING_DELETION_REJECTED',
  DELETE_PENDING_DELETION_FULFILLED: 'DELETE_PENDING_DELETION_FULFILLED'

};
