export default {

	POEM_CHANGED: 'POEM_CHANGED',

	GET_POEM_REQUESTED: 'GET_POEM_REQUESTED',
	GET_POEM_REJECTED: 'GET_POEM_REJECTED',
	GET_POEM_FULFILLED: 'GET_POEM_FULFILLED',
	
	CREATE_POEM_REQUESTED: 'CREATE_POEM_REQUESTED',
	CREATE_POEM_REJECTED: 'CREATE_POEM_REJECTED',
	CREATE_POEM_FULFILLED: 'CREATE_POEM_FULFILLED',

	UPDATE_POEM_REQUESTED: 'UPDATE_POEM_REQUESTED',
	UPDATE_POEM_REJECTED: 'UPDATE_POEM_REJECTED',
	UPDATE_POEM_FULFILLED: 'UPDATE_POEM_FULFILLED',
	
	DELETE_POEM_REQUESTED: 'DELETE_POEM_REQUESTED',
	DELETE_POEM_REJECTED: 'DELETE_POEM_REJECTED',
	DELETE_POEM_FULFILLED: 'DELETE_POEM_FULFILLED',
	
};