// export default {

// 	VERSIONS_CHANGED: 'VERSIONS_CHANGED',

// 	CREATE_VERSION_REQUESTED: 'CREATE_VERSION_REQUESTED',
// 	CREATE_VERSION_REJECTED: 'CREATE_VERSION_REJECTED',
// 	CREATE_VERSION_FULFILLED: 'CREATE_VERSION_FULFILLED',

// };